name: DevOps CI - Tests + Docker Bake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  # JOB 1: TESTS
 
  tests:
    runs-on: ubuntu-latest

    env:
      # Forzamos valores fijos para que no rompa los snapshots
      GITHUB_RUN_ID: 123456789
      GITHUB_RUN_ATTEMPT: 1

    defaults:
      run:
        working-directory: ./bake-action

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: bake-action/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npm test


  # JOB 2: DOCKER BAKE

  docker-bake:
    needs: tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bake-action

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ejecutar Docker Bake (solo build, sin push)
        uses: docker/bake-action@v5
        with:
          files: ./bake-action/test/config.hcl
          targets: default
          push: false
